"""Add student profile fields

Revision ID: 32e80d5c2aee
Revises: f2d2ae320938
Create Date: 2026-07-16 12:14:43.531699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e80d5c2aee'
down_revision = 'f2d2ae320938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('blood_group', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('address')
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('blood_group')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
